### ISSUE TITLE
Observe flag

### ISSUE THREAD

**Issue by rsmallegoor** [1248/microcoap#25]
Is it true that the observe option is not yet implemented in the GET function? Thanks,

Roel

**Comment by tobyjaffey** [comment]
On 2 Jul 2015, at 10:45, rsmallegoor <notifications@github.com> wrote:

> Is it true that the observe option is not yet implemented in the GET function? Thanks,

That is right, yes.

�

**Comment by a-andreyev** [comment]
@rsmallegoor, I'm working to add coap observe option within [SemIoT project](http://semiot.ru/en/index.html).
Currently we have draft version with initial subscrube support for arduino mega board and esp8266 wifi module. I'm going to contribute to microcoap project when more tests will be passed. Feel free to ask any questions. [Our subscribe implementation for arduino device with esp8266 wifi module](https://github.com/semiotproject/iot-device-first-prototype)

**Comment by rsmallegoor** [comment]
Hi Alexey,

That sounds good. I am implementing CoAP on a linux based system (pcDuino).
Unfortunately the pcDuino is not able to (properly) run Arduino scripts,
that is why i was looking at the more general microcoap.

Roel

2015-07-02 12:58 GMT+02:00 Alexey Andreyev <notifications@github.com>:

**Comment by a-andreyev** [comment]
Hello, Roel! Got it!
As I understood, microcoap was created to support both arduino and linux-based devices. I hope when it will be ready, I can contribute to support observing both for arduino and posix systems too.

**Comment by rsmallegoor** [comment]
Hi,

Yes, that is true. That is why i wanted to use it for a Smart Factory
demonstrator set-up. But for that i really need the observe option. I am
now trying to use the Java based Californium, it offers all the CoAP
possibilities.

Good luck with your project!

2015-07-02 15:00 GMT+02:00 Alexey Andreyev <notifications@github.com>:

**Comment by a-andreyev** [comment]
Thank you! You too!
